import React from "react";
import { Link } from "react-router-dom";
import { motion } from "motion/react";
import { CheckCircle2, Sparkles, Target, Zap } from "lucide-react";

export default function Landing() {
  return (
    <div className="relative overflow-hidden">
      {/* Hero Section */}
      <section className="relative px-6 pt-24 pb-32 sm:pt-32 lg:px-8">
        <div className="mx-auto max-w-7xl text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <h1 className="text-5xl font-extrabold tracking-tight text-neutral-900 sm:text-7xl">
              Master Your Next <span className="text-indigo-600">Technical Interview</span>
            </h1>
            <p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-neutral-600">
              Practice with our AI-powered interviewer. Get real-time feedback, improve your coding skills, and land your dream job at top tech companies.
            </p>
            <div className="mt-10 flex items-center justify-center gap-x-6">
              <Link
                to="/signup"
                className="rounded-full bg-indigo-600 px-8 py-4 text-lg font-semibold text-white shadow-xl hover:bg-indigo-700 transition-all hover:scale-105"
              >
                Start Practicing Free
              </Link>
              <Link to="/login" className="text-sm font-semibold leading-6 text-neutral-900">
                View Demo <span aria-hidden="true">→</span>
              </Link>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features Section */}
      <section className="bg-white py-24 sm:py-32">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="mx-auto max-w-2xl lg:text-center">
            <h2 className="text-base font-semibold leading-7 text-indigo-600 uppercase tracking-widest">Why InterviewPro?</h2>
            <p className="mt-2 text-3xl font-bold tracking-tight text-neutral-900 sm:text-4xl">
              Everything you need to succeed
            </p>
          </div>
          <div className="mx-auto mt-16 max-w-2xl sm:mt-20 lg:mt-24 lg:max-w-none">
            <dl className="grid max-w-xl grid-cols-1 gap-x-8 gap-y-16 lg:max-w-none lg:grid-cols-3">
              {[
                {
                  name: "AI-Powered Questions",
                  description: "Dynamic questions tailored to your role and difficulty level, generated by Google Gemini.",
                  icon: Sparkles,
                },
                {
                  name: "Instant Feedback",
                  description: "Get detailed ratings, strengths, and areas for improvement immediately after each answer.",
                  icon: Zap,
                },
                {
                  name: "Real Simulations",
                  description: "Experience the pressure of a real interview with timed sessions and behavioral tracking.",
                  icon: Target,
                },
              ].map((feature) => (
                <div key={feature.name} className="flex flex-col items-start p-8 rounded-3xl bg-neutral-50 border border-black/5">
                  <div className="rounded-2xl bg-indigo-600 p-3 text-white mb-6">
                    <feature.icon className="h-6 w-6" aria-hidden="true" />
                  </div>
                  <dt className="text-xl font-bold leading-7 text-neutral-900">{feature.name}</dt>
                  <dd className="mt-4 flex flex-auto flex-col text-base leading-7 text-neutral-600">
                    <p className="flex-auto">{feature.description}</p>
                  </dd>
                </div>
              ))}
            </dl>
          </div>
        </div>
      </section>
    </div>
  );
}
